import Vue from 'vue'
import { Button, NavBar, Field, CellGroup, Toast, CountDown, Tabbar, TabbarItem, Cell, Image, Grid, GridItem, Icon, Tab, Tabs, List, PullRefresh, ActionSheet } from 'vant'
Vue.use(Button)
  .use(NavBar)
  .use(Field)
  .use(CellGroup)
  .use(Toast)
  .use(CountDown)
  .use(Tabbar)
  .use(TabbarItem)
  .use(Cell)
  .use(Image)
  .use(Grid)
  .use(GridItem)
  .use(Icon)
  .use(Tab)
  .use(Tabs)
  .use(List)
  .use(PullRefresh)
  .use(ActionSheet)
